#!/usr/bin/env python3
"""Sync Azure AI Foundry deployments into ~/.omp/agent/models.yml as an omp provider.

Setup on a new machine (only this file needs copying):

    python3 foundry-sync.py \
        --endpoint https://<resource>.services.ai.azure.com \
        --set-key  <foundry-api-key>

That writes ~/.omp/agent/.env (mode 600), then regenerates the provider block.
Afterwards a bare `python3 foundry-sync.py` re-reads credentials from the
environment or ~/.omp/agent/.env. Rotating a key needs only `--set-key`.

Every deployment is served by the Foundry v1 Responses surface
(POST {endpoint}/openai/v1/responses) behind one URL and one `api-key` header --
OpenAI, Anthropic, xAI, Moonshot, DeepSeek and Mistral alike. Model ids are the
*deployment* names, so no AZURE_OPENAI_DEPLOYMENT_NAME_MAP is required.

Re-run after adding or removing deployments, then restart omp.
Requires only the Python standard library; PyYAML is used when present to
preserve unrelated providers in an existing models.yml.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

AGENT_DIR = Path(os.environ.get("PI_CODING_AGENT_DIR", Path.home() / ".omp" / "agent"))
MODELS_YML = AGENT_DIR / "models.yml"
ENV_FILE = AGENT_DIR / ".env"
PROVIDER_ID = os.environ.get("FOUNDRY_PROVIDER_ID", "foundry")
LIST_API_VERSION = "2023-03-15-preview"
SENTINEL = "# generated by foundry-sync.py -- edits are overwritten"

# (context window, max output tokens, reasoning, accepts images)
# Conservative published limits per family; edit if a deployment differs.
FAMILIES: list[tuple[tuple[str, ...], tuple[int, int, bool, bool]]] = [
    (("gpt-5", "gpt-chat-latest", "model-router"), (400_000, 128_000, True, True)),
    (("o3", "o1", "o4"), (200_000, 100_000, True, True)),
    (("gpt-4-1", "gpt-4.1"), (1_047_576, 32_768, False, True)),
    (("gpt-4o",), (128_000, 16_384, False, True)),
    (("claude-opus", "claude-sonnet", "claude-haiku", "claude-fable"), (200_000, 64_000, True, True)),
    (("grok",), (256_000, 32_768, True, True)),
    (("kimi",), (256_000, 32_768, True, False)),
    (("deepseek",), (128_000, 32_768, True, False)),
    (("mai-thinking",), (128_000, 32_768, True, False)),
    (("llama-4",), (128_000, 16_384, False, True)),
    (("llama-3",), (128_000, 16_384, False, False)),
    (("mistral", "ministral", "codestral"), (128_000, 16_384, False, False)),
    (("phi-4-multimodal",), (128_000, 16_384, False, True)),
    (("phi-4-reasoning", "phi-4-mini-reasoning"), (128_000, 16_384, True, False)),
    (("phi-4",), (128_000, 16_384, False, False)),
    (("cohere",), (256_000, 16_384, False, False)),
    (("gpt-oss",), (128_000, 32_768, True, False)),
]
DEFAULT_META = (128_000, 16_384, False, False)


def read_env_file() -> dict[str, str]:
    if not ENV_FILE.is_file():
        return {}
    values: dict[str, str] = {}
    for raw in ENV_FILE.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, _, value = line.partition("=")
        values[name.strip()] = value.strip().strip("'\"")
    return values


def write_env_file(values: dict[str, str]) -> None:
    AGENT_DIR.mkdir(parents=True, exist_ok=True)
    body = [
        "# Azure AI Foundry credentials for omp's `foundry` provider.",
        "# AZURE_OPENAI_API_KEY is referenced by name from models.yml.",
    ]
    body += [f"{name}={values[name]}" for name in sorted(values)]
    ENV_FILE.write_text("\n".join(body) + "\n")
    ENV_FILE.chmod(0o600)


def meta_for(deployment_id: str) -> tuple[int, int, bool, bool]:
    lowered = deployment_id.lower()
    for prefixes, meta in FAMILIES:
        if any(lowered.startswith(p) for p in prefixes):
            return meta
    return DEFAULT_META


def fetch_deployments(endpoint: str, key: str) -> list[dict]:
    url = f"{endpoint}/openai/deployments?api-version={LIST_API_VERSION}"
    request = urllib.request.Request(url, headers={"api-key": key})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = json.load(response)
    except urllib.error.HTTPError as exc:
        detail = exc.read()[:300].decode(errors="replace")
        sys.exit(f"listing deployments failed: HTTP {exc.code} {detail}")
    except urllib.error.URLError as exc:
        sys.exit(f"cannot reach {endpoint}: {exc.reason}")
    return [d for d in payload.get("data", []) if d.get("status") == "succeeded"]


def build_provider(endpoint: str, deployments: list[dict]) -> dict:
    models = []
    for dep in sorted(deployments, key=lambda d: d["id"].lower()):
        context_window, max_tokens, reasoning, vision = meta_for(dep["id"])
        entry = {
            "id": dep["id"],
            "name": f"{dep.get('model', dep['id'])} (Foundry)",
            "contextWindow": context_window,
            "maxTokens": max_tokens,
            "input": ["text", "image"] if vision else ["text"],
        }
        if reasoning:
            entry["reasoning"] = True
        models.append(entry)
    return {
        "baseUrl": f"{endpoint}/openai/v1",
        "api": "azure-openai-responses",
        "apiKey": "AZURE_OPENAI_API_KEY",
        "compat": {
            "strictResponsesPairing": True,
            "supportsDeveloperRole": True,
            "supportsStore": False,
        },
        "models": models,
    }


def emit_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if text != text.strip() or not text or text[0] in "&*?|-<>=!%@`\"'{}[]#,":
        return json.dumps(text)
    return text


def emit_yaml(node: object, indent: int = 0) -> list[str]:
    """Minimal YAML emitter for the plain dict/list/scalar tree used here."""
    pad = "  " * indent
    lines: list[str] = []
    if isinstance(node, dict):
        for key, value in node.items():
            if isinstance(value, (dict, list)) and value:
                lines.append(f"{pad}{key}:")
                lines += emit_yaml(value, indent + 1)
            elif isinstance(value, (dict, list)):
                lines.append(f"{pad}{key}: {{}}" if isinstance(value, dict) else f"{pad}{key}: []")
            else:
                lines.append(f"{pad}{key}: {emit_scalar(value)}")
    elif isinstance(node, list):
        for item in node:
            if isinstance(item, dict) and item:
                nested = emit_yaml(item, indent + 1)
                lines.append(f"{pad}- {nested[0].lstrip()}")
                lines += nested[1:]
            else:
                lines.append(f"{pad}- {emit_scalar(item)}")
    return lines


def merge_document(provider: dict) -> dict:
    document: dict = {"providers": {}}
    if MODELS_YML.is_file():
        text = MODELS_YML.read_text()
        if yaml is not None:
            existing = yaml.safe_load(text) or {}
            if isinstance(existing, dict):
                document = existing
                document.setdefault("providers", {})
        elif SENTINEL not in text:
            sys.exit(
                f"{MODELS_YML} was not written by this script and PyYAML is unavailable, so other\n"
                "providers in it cannot be preserved. Install PyYAML (pip install pyyaml) or move\n"
                "the file aside before re-running."
            )
    document["providers"][PROVIDER_ID] = provider
    return document


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync Azure AI Foundry deployments into omp's models.yml")
    parser.add_argument("--endpoint", help="Foundry endpoint, e.g. https://<resource>.services.ai.azure.com")
    parser.add_argument("--set-key", dest="set_key", help="store/rotate the Foundry API key in ~/.omp/agent/.env")
    args = parser.parse_args()

    env_values = read_env_file()
    if args.endpoint or args.set_key:
        if args.endpoint:
            env_values["AZURE_FOUNDRY_ENDPOINT"] = args.endpoint.rstrip("/")
        if args.set_key:
            env_values["AZURE_OPENAI_API_KEY"] = args.set_key
        write_env_file(env_values)
        print(f"updated {ENV_FILE}")

    endpoint = (os.environ.get("AZURE_FOUNDRY_ENDPOINT") or env_values.get("AZURE_FOUNDRY_ENDPOINT", "")).rstrip("/")
    key = os.environ.get("AZURE_OPENAI_API_KEY") or env_values.get("AZURE_OPENAI_API_KEY", "")
    if args.set_key:
        key = args.set_key
    if not endpoint or not key:
        sys.exit(
            "missing credentials. Pass --endpoint/--set-key once, or set AZURE_FOUNDRY_ENDPOINT\n"
            "and AZURE_OPENAI_API_KEY in the environment or ~/.omp/agent/.env"
        )

    deployments = fetch_deployments(endpoint, key)
    if not deployments:
        sys.exit("no succeeded deployments returned")

    provider = build_provider(endpoint, deployments)
    document = merge_document(provider)

    AGENT_DIR.mkdir(parents=True, exist_ok=True)
    if yaml is not None:
        body = yaml.safe_dump(document, sort_keys=False, width=120)
    else:
        body = "\n".join(emit_yaml(document)) + "\n"
    MODELS_YML.write_text(f"{SENTINEL}\n{body}")

    print(f"wrote {len(provider['models'])} models to {MODELS_YML} under provider '{PROVIDER_ID}'")
    print(f"endpoint: {provider['baseUrl']}")


if __name__ == "__main__":
    main()
